# Window sizes
SETTINGS_WINDOW_GEOMETRY = "450x570"

# Padding
FRAME_PADDING = "10"
BUTTON_PADDING_X = 5
BUTTON_PADDING_Y = 5

# History settings
HISTORY_LIMIT_MIN = 10
HISTORY_LIMIT_MAX = 1000
HISTORY_LIMIT_INCREMENT = 10
